### ISSUE TITLE
Tweets stop streaming after Z_BUF_ERROR

### ISSUE THREAD

**Issue by mcorb** [ttezel/twit#247]
Using current twit HEAD, streaming fails to continue after this error is encountered, usually after a day or so of use:

  { [Error: unexpected end of file] errno: -5, code: 'Z_BUF_ERROR' }

It looks like there's a problem with gzip/zlib and the library is failing to reconnect for some reason?

**Comment by mcorb** [comment]
I've updated to HEAD / 2.2.3, and there's a change in behavior:

The new behaviour: after a couple of days streaming, the Z_BUF_ERROR still happens, but now an 'error' event is thrown.

In our app we don't yet handle 'error', so our app crashes and restarts, which is an improvement on the old behaviour, because it usually reconnects after the restart, and we don't loose many tweets.

Are consumers expected to handle 'error' manually now? Is there guidance on how to trigger a reconnect?

(With older versions of twit.js we were able to stream for months without any special error handling. Any idea why we're starting to hit Z_BUF_ERROR so frequently now?)


{ [Error: unexpected end of file] errno: -5, code: 'Z_BUF_ERROR' }
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 199.16.156.217:443
    at Object.exports._errnoException (util.js:855:11)
    at exports._exceptionWithHostPort (util.js:878:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
error: Forever detected script exited with code: 1
error: Script restart attempt #1

**Comment by IceSofticon30th** [comment]
When I push the "Revoke access" button on the Twitter Settings Page(https://twitter.com/settings/applications), my app always crashes immediately in spite of handling error event Twit emits.

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: unexpected end of file
    at Zlib._handle.onerror (zlib.js:363:17)

**Comment by LTheobald** [comment]
I've tried to use Twit for the first time today & with my very simple example (https://gist.github.com/LTheobald/f7fa0bb4538e3bec34df), I get Z_BUF_ERROR's logged after a few seconds. Is that something I'm doing or is there an underlying issue?

**Comment by ttezel** [comment]
@LTheobald are you providing actual credentials to Twit? In your code you pass in strings like '...'.

**Comment by LTheobald** [comment]
@ttezel Yes, I had omitted the authentication details as I didn't wamt to share my secret key etc. Sorry - should have added a comment in the code explaining that.

On a side note, for me I only see to get the Z_BUF_ERR when I enter valid details. So if I run the code with the invalid '...' options in there, I don't get any errors. Put my valid details in, Z_BUF_ERR after a few seconds.

**Comment by funador** [comment]
I am having the same problem.  Tried to handle the error with: 

`stream.on('error', (err) => {
      console.error("Twitter Stream Err------", err)
      console.log("stopping stream");
      stream.stop()

      setTimeout(function () {
        console.log('starting stream')
        stream.start()
      }, 2000)
    })`

But that doesn't seem to work.  Timeout is just to give a slight pause before trying a new connection.  Any one have ideas on how to trigger the error so we can test against it better?  Like @mcorb the error is only occurring for me after a day or so which is quite frustrating.  I am not worried about missing a few tweets, more about stability.

**Comment by underscoredotspace** [comment]
It's not making me happy, but I have the below workaround that seems to work so far. Forced reload like @funador's, but only the Twit stream rather than the whole app (which for me has other implications). 

````javascript
stream.on('error', function(error) {
  console.log(Date() + ': error - ');
  console.error(JSON.stringify(error));
  if (error.errno == -5) {
    console.log('error -5 caught');
    stream.stop();
    setTimeout (function () {
      stream.start();
    }, 5000);
  }
  console.log('end of error');
});
````

**Comment by ttezel** [comment]
Hey guys, I think this was due to a timestamp issue, and this has been fixed in twit v2.2.4. Run `npm update twit` to get it, and please let me know if you have issues! Thanks!!

**Comment by MeanwhileMedia** [comment]
I'm using v2.2.4 and am still experiencing the same problem.

**Comment by MeanwhileMedia** [comment]
Changing this line:
https://github.com/ttezel/twit/blob/master/lib/streaming-api-connection.js#L89
To:
```
var gunzip = zlib.createGunzip({finishFlush: zlib.Z_SYNC_FLUSH});
```
Will prevent the process from crashing. However, there is no twit reconnect attempt when it occurs.

**Comment by olalonde** [comment]
I'm also seeing that bug with 2.2.4.

Here's some server logs:

```javscript
info: Connecting to Twitter stream
info: Connected to Twitter stream
{ Error: unexpected end of file
    at Zlib._handle.onerror (zlib.js:370:17) errno: -5, code: 'Z_BUF_ERROR' }
error:  Error: unexpected end of file
    at Zlib._handle.onerror (zlib.js:370:17)
info: Connecting to Twitter stream
info: Connected to Twitter stream
{ Error: unexpected end of file
    at Zlib._handle.onerror (zlib.js:370:17) errno: -5, code: 'Z_BUF_ERROR' }
error:  Error: unexpected end of file
    at Zlib._handle.onerror (zlib.js:370:17)
info: Connecting to Twitter stream
info: Connected to Twitter stream
{ Error: unexpected end of file
    at Zlib._handle.onerror (zlib.js:370:17) errno: -5, code: 'Z_BUF_ERROR' }
error:  Error: unexpected end of file
    at Zlib._handle.onerror (zlib.js:370:17)
info: Connecting to Twitter stream
info: Connected to Twitter stream
{ Error: unexpected end of file
    at Zlib._handle.onerror (zlib.js:370:17) errno: -5, code: 'Z_BUF_ERROR' }
error:  Error: unexpected end of file
    at Zlib._handle.onerror (zlib.js:370:17)
info: Connecting to Twitter stream
info: Connected to Twitter stream
```

Here's my code:

```javascript
    const stream = twitter.stream('statuses/filter', {
      track: '#somehashtag',
    })
    stream.on('tweet', (tweet) => (
      processTweet(tweet)
        .catch((err) => {
          const tweetUrl = `https://twitter.com/statuses/${tweet.id_str}`
          console.error(`Error while processing ${tweetUrl}`)
          console.error(err.stack)
        })
    ))
    stream.on('connect', () => {
      logger.info('Connecting to Twitter stream')
    })
    stream.on('connected', () => {
      logger.info('Connected to Twitter stream')
    })
    stream.on('disconnect', () => {
      logger.info('Disconnected from Twitter stream')
    })
    stream.on('error', (err) => {
      console.error(err)
      logger.error(err)
    })
```

As you can see, I'm not throwing the error in my error event handler so I suppose some kind of reconnect mechanism was added to `twit.stream`?
